### PR TITLE
Add CDN and badge

### PR DESCRIPTION
**Pull request by fonsdant**

### CODE REVIEW

**Comment by sroehrl** [comment]
Thank you! Gaudiamus is intended to be installed locally to enable it's goal to "roll your own" CSS behavior/framework. The CDN solution does not provide that benefit and is simply a "quick try-out" solution. I would like to have a disclaimer that explains that fact well.

**Comment by fonsdant** [comment]
Alright, I have a new commit. I expect that this one may attend you. I took as base <https://gaudiamus-css.github.io/> and your last comment. Let me know if there are any others notes.

**Review by sroehrl — APPROVED** [review]
Thank you very much. Approved!

**Comment by fonsdant** [comment]
I'm feel good to contribute 🤝

**Pull request merged**
